#!/usr/bin/env bash
# execute_transfers.sh — execute the consolidation plan against GitHub.
#
# *** Phase B. Dry-run by default. Refuses to mutate without --execute. ***
#
# Reads:  ${SCRUTATOR_DATA:-data}/inventory/repos.categorized.jsonl
# Writes: ${SCRUTATOR_DATA:-data}/inventory/transfer-log.jsonl
#
# Processes buckets in safety order:
#   1. rename_then_transfer (rename source to <basename>-legacy, then transfer)
#   2. transfer_archived
#   3. transfer_private
#   4. transfer_public
# Skips: keep_on_profile, defer_fork, skip_*, anything else.

set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 [--execute] [--only BUCKET] [--yes] [--target ORG] [--help]

Execute the consolidation plan generated by render_transfer_plan.sh.

Flags:
  --execute        Actually perform transfers. Without this, prints planned
                   actions only (dry run). REQUIRED for any state change.
  --only BUCKET    Process only the named bucket
                   (rename_then_transfer | transfer_archived |
                    transfer_private | transfer_public).
                   May be repeated. Default: all four transfer buckets.
  --yes            Skip the interactive confirmation prompt.
  --target ORG     Target org. Default: meta-organvm (or \$SCRUTATOR_TARGET_ORG).
  -h, --help       Show this message.

Preconditions:
  - scripts/inventory_repos.sh, categorize_repos.sh, render_transfer_plan.sh
    have all been run.
  - transfer-plan.md exists and (in --execute mode) is committed.
  - gh PAT scopes: repo, admin:org.

Outputs:
  data/inventory/transfer-log.jsonl  — one JSON object per attempted action,
                                       appended (not truncated) across runs.
EOF
}

EXECUTE=0
YES=0
ONLY_BUCKETS=()
TARGET="${SCRUTATOR_TARGET_ORG:-meta-organvm}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --execute) EXECUTE=1; shift ;;
    --yes)     YES=1; shift ;;
    --only)    ONLY_BUCKETS+=("$2"); shift 2 ;;
    --target)  TARGET="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

DATA_DIR="${SCRUTATOR_DATA:-data}/inventory"
IN="${DATA_DIR}/repos.categorized.jsonl"
PLAN_MD="${DATA_DIR}/transfer-plan.md"
LOG="${DATA_DIR}/transfer-log.jsonl"

[[ -f "$IN" ]] || { echo "error: $IN not found; run scripts/categorize_repos.sh first" >&2; exit 1; }
[[ -f "$PLAN_MD" ]] || { echo "error: $PLAN_MD not found; run scripts/render_transfer_plan.sh first" >&2; exit 1; }
command -v jq >/dev/null || { echo "error: jq not installed" >&2; exit 1; }
if [[ "$EXECUTE" == "1" ]]; then
  command -v gh >/dev/null || { echo "error: gh CLI not installed" >&2; exit 1; }
  gh auth status >/dev/null 2>&1 || { echo "error: gh not authenticated" >&2; exit 1; }
fi

# Default to all four transfer buckets if --only not provided.
if [[ ${#ONLY_BUCKETS[@]} -eq 0 ]]; then
  ONLY_BUCKETS=(rename_then_transfer transfer_archived transfer_private transfer_public)
fi

# Confirm.
if [[ "$EXECUTE" == "1" && "$YES" != "1" ]]; then
  echo "About to execute transfers to '${TARGET}'." >&2
  echo "Buckets: ${ONLY_BUCKETS[*]}" >&2
  echo "Log: ${LOG}" >&2
  printf "Continue? [y/N] " >&2
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "aborted" >&2; exit 1; }
fi

mkdir -p "$(dirname "$LOG")"
touch "$LOG"

log_event() {
  local row="$1" event="$2" outcome="$3" detail="${4:-}"
  jq -nc \
    --argjson row "$row" \
    --arg event "$event" \
    --arg outcome "$outcome" \
    --arg detail "$detail" \
    --arg ts "$(date -Iseconds)" \
    --arg target "$TARGET" \
    --argjson execute "$EXECUTE" \
    '{ts: $ts, target: $target, execute: ($execute==1), event: $event, outcome: $outcome, detail: $detail, full_name: $row.full_name, action: $row.action}' \
    >> "$LOG"
}

run_gh() {
  # In dry-run, print only. In execute, run and capture status.
  local row="$1" event="$2"; shift 2
  if [[ "$EXECUTE" != "1" ]]; then
    echo "  DRY-RUN: gh $*"
    log_event "$row" "$event" "dry_run" "$(printf '%s ' "$@")"
    return 0
  fi
  if gh "$@" >/dev/null 2>&1; then
    log_event "$row" "$event" "ok" "$(printf '%s ' "$@")"
    return 0
  else
    log_event "$row" "$event" "fail" "$(printf '%s ' "$@")"
    return 1
  fi
}

process_bucket() {
  local bucket="$1"
  echo "==> $bucket"
  jq -c --arg b "$bucket" 'select(.action == $b)' "$IN" | while read -r row; do
    local full_name owner base
    full_name=$(jq -r '.full_name' <<<"$row")
    owner=$(jq -r '.owner' <<<"$row")
    base=$(jq -r '.full_name | split("/")[1]' <<<"$row")
    echo "  - $full_name -> ${TARGET}/${base}"

    case "$bucket" in
      rename_then_transfer)
        # Rename source first, then transfer the renamed source via REST API.
        # The renamed name MUST be unique in the target org, because multiple
        # source orgs can share the same basename (e.g. every org has a
        # `.github` repo). Prefix with source owner to disambiguate.
        local renamed="${owner}-${base}-legacy"
        local rename_args=(repo rename "$renamed" --repo "$full_name")
        [[ "$YES" == "1" ]] && rename_args+=(--yes)
        run_gh "$row" "rename" "${rename_args[@]}" || { echo "    (rename failed; skipping)"; continue; }
        run_gh "$row" "transfer" api -X POST "repos/${owner}/${renamed}/transfer" -f "new_owner=${TARGET}" || echo "    (transfer failed)"
        ;;
      transfer_archived|transfer_private|transfer_public)
        run_gh "$row" "transfer" api -X POST "repos/${full_name}/transfer" -f "new_owner=${TARGET}" || echo "    (transfer failed)"
        ;;
      *)
        echo "    (unknown bucket; skipping)"; continue
        ;;
    esac
  done
}

for b in "${ONLY_BUCKETS[@]}"; do
  process_bucket "$b"
done

echo "" >&2
if [[ "$EXECUTE" == "1" ]]; then
  echo "Done. Log: $LOG" >&2
  echo "Verify each row with: gh repo view ${TARGET}/<basename>" >&2
else
  echo "Dry run complete. Re-run with --execute to apply." >&2
fi
